   <!-- footer content -->
        <footer>
          <div class="pull-right">
            
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
   <!-- <script src="../../vendors/jquery/dist/jquery.min.js"></script> -->
    <!-- Bootstrap -->
   <!-- <script src="../../vendors/bootstrap/dist/js/bootstrap.min.js"></script> -->

   <!-- jQuery 3.6.0 -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Bootstrap 4 JS (or higher) -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

 
<!-- Select2 CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/css/select2.min.css" rel="stylesheet" />

<!-- Select2 JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0-rc.0/js/select2.min.js"></script>


    <!-- Custom Theme Scripts -->
    <script src="../../build/js/custom.min.js"></script>
  <script src="js/fas.js"></script>
  <script>
      $(document).ready(function() {
          // Initialize Select2
          $('select').select2();
      });
    </script>
  
  <?php include 'script.php'; ?>

 